import { Router } from 'express';
import { templateController } from '../controllers/template.controller';

const router = Router();

router.get('/', templateController.getAvailableTemplates);

// Expose a direct endpoint that returns a graphical PNG thumbnail generated by Puppeteer
router.get('/:id/preview', templateController.generatePreview);

export default router;
